### ISSUE TITLE
Exception running ValidateCramFile

### ISSUE THREAD

**Issue by hreuver** [enasequence/cramtools#17]
Best,

We would like to use CRAMtools to archive large amounts of BAM files. We want to make sure the proces of cramming went without problems and therefor we run ValidateCramFile afterward. 

Yesterday I crammed about 400 BAM files. For all files I ran ValidateCramFile like this:

java -cp /share/apps/cramtools-2.1.jar net.sf.cram.ValidateCramFile -I /scratch/DNAXXXXX.cram -R /data/references/GrCh37/GrCh37_reference.fa

For all 400 samples I run into the following exception:

Exception in thread "main" net.sf.samtools.SAMException: Exception counting mismatches for read 4923571 1/2 100b aligned read.
        at net.sf.samtools.util.SequenceUtil.countMismatches(SequenceUtil.java:296)
        at net.sf.samtools.util.SequenceUtil.calculateSamNmTag(SequenceUtil.java:481)
        at net.sf.picard.sam.SamFileValidator.validateNmTag(SamFileValidator.java:461)
        at net.sf.picard.sam.SamFileValidator.validateSamRecords(SamFileValidator.java:296)
        at net.sf.cram.ValidateCramFile.main(ValidateCramFile.java:116)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 142535434
        at net.sf.samtools.util.SequenceUtil.countMismatches(SequenceUtil.java:282)
        ... 4 more

Does someone know what goes wrong and what I can do to fix this?

Many thanks,

Rick

**Comment by vadimzalunin** [comment]
Hi Rick,

Have you tried converting the CRAM files back to BAM?

All I can see from the stacktrace is that probably the reference is 
shorter than expected: 142535434 causes ArrayOutOfIndexException. Are 
there reads mapped beyond the reference?

Vadim

**Comment by hreuver** [comment]
Hi Vadim,

Converting from CRAM to BAM seems to go Ok: no exceptions or error messages. I didn't recall the variants and compared them with our previous calls though. Since we are planning to archive thousands of BAM files a year, we would like to be as sure as possible no problems occured during conversion from BAM to CRAM. I really would like to have some kind of validation.

When I look at the header of a BAM and CRAM file all chromosome lengths match with the chromosome lengths of our reference genome (hg19 + contigs). it seems therefor unlikely that reads are mapped outside the reference genome, but I could be wrong. 

Is there a wat to extract a read from a CRAM file based on an index (4923571 in this case) to see where it is mapped. Is there an easy way to check wether reads are mapped outside the reference genome?

Many thanks,

Rick

**Comment by vadimzalunin** [comment]
On 29/01/2015 10:04, hreuver wrote:
>
> Hi Vadim,
>
> Converting from CRAM to BAM seems to go Ok: no exceptions or error 
> messages. I didn't recall the variants and compared them with our 
> previous calls though. Since we are planning to archive thousands of 
> BAM files a year, we would like to be as sure as possible no problems 
> occured during conversion from BAM to CRAM. I really would like to 
> have some kind of validation.
>
> When I look at the header of a BAM and CRAM file all chromosome 
> lengths match with the chromosome lengths of our reference genome 
> (hg19 + contigs). it seems therefor unlikely that reads are mapped 
> outside the reference genome, but I could be wrong.
>
> Is there a wat to extract a read from a CRAM file based on an index 
> (4923571 in this case) to see where it is mapped. Is there an easy way 
> to check wether reads are mapped outside the reference genome?
>
By mapped beyond reference I mean that a few bases of a read are mapped 
beyond reference. I suspect that the coding/decoding code works fine but 
the validation tool has the bug.
To check if there are hanging reads I'd try tview from samtools, jump to 
the end of the reference sequence and see if there extra read bases.

Vadim

**Comment by hreuver** [comment]
Hi Vadim,

I finally had time to look into the problem and you are right. There is overhang with chromosomes. If we look at the following exception...
<code>
Exception in thread "main" net.sf.samtools.SAMException: Exception counting mismatches for read 5281214 2/2 100b aligned read.
        at net.sf.samtools.util.SequenceUtil.countMismatches(SequenceUtil.java:296)
        at net.sf.samtools.util.SequenceUtil.calculateSamNmTag(SequenceUtil.java:481)
        at net.sf.picard.sam.SamFileValidator.validateNmTag(SamFileValidator.java:461)
        at net.sf.picard.sam.SamFileValidator.validateSamRecords(SamFileValidator.java:296)
        at net.sf.cram.ValidateCramFile.main(ValidateCramFile.java:116)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 142535434
        at net.sf.samtools.util.SequenceUtil.countMismatches(SequenceUtil.java:282)
        ... 4 more </code>

... and locate the read(s) that throw the exception...

<code><7<BB<B<FFFFFF<7FFFBBFFFBBFFFF<FFFBBB7FFB7IFIFFFFFFF7FFBFFB<BB7<0IFFIFBBBFFBFFFBBB<<7B< MD:Z:0N0N0N0N0N0N0N0N0N0N0N0N0N0N0^N0N0N0N0N0N0N0       NM:i:21 RG:Z:EXON130819134-12-01307-22
DNA1308883U.cram:528:1213       163     chr1    142535435       29      40S60M  =       142535601       266     GAATGGAATTGAAAGGAATACAATTGAATGTAATGCAATGGAATTTAATGGAATGGAATTCAATGGAATGCAATGAAATACAATGGAATGGAATGCAATG    BBBFFFFFFFFFFIIIIIIIIIIIIIIIIIFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFFFFFFFFFFFBFFBBBBF MD:Z:5C54       NM:i:1  RG:Z:EXON130819134-12-01307-22
DNA1308883U.cram:528:1214       163     chr1    142535435       29      19S81M  =       142535602       258     AATTGAATGTAATGCAATGGAATTCAATGGAATGGAATTCAATGGAATGCAATGAAATACAATGGAATGGAATGCAATGCAATGCAATGCAATGGAATGC    BB<FF<<B00BBFFFBFFFFFIIBBFFIFFI<BFFBFFBFFBFFFFFFBFFFIIBBBFFFFBFFBBFFIIIIIFBBBBBFFFFFFBBBFFFFFBBBB<BB MD:Z:81 NM:i:0  RG:Z:EXON130819134-12-01307-22</code>

... we clearly see that the first bases are trimmed. Samtools tview shows it even better:

![capture](https://cloud.githubusercontent.com/assets/10669181/6019817/19d91ebc-aba5-11e4-91e3-8856910012f0.PNG)

Will this bug be fixed and if so, could you/someone give an estimation when we can expect the patch/release with the solution? This so we can adjust our strategy towards data archiving. 

Many thanks,

Rick

**Comment by vadimzalunin** [comment]
Hi Rick,

I'm lost here because the reads are mapped beyond 142535434 and tview 
shows reference longer than 142535434 but guessing from the stack trace 
the reference is shorter than that. What is the actual reference 
sequence length? It should be in the FAI fasta index file but I'd check 
the fasta file as well just in case.

Vadim

Sure, I can fix it. To get to the bottom of this I need to know what's 
in the original data. In particular 40S60M cigar suggests that the 60 
bases are mapped to the reference whereas some of them are not - the 
reference does not exist there.
Additionally, the mate's position is 142535601, which is even further 
down on the reference. Possible scenarios:
1. A different (longer) reference sequence was used by aligner.
2. Aligner produced invalid alignment.
3. Bug in Bam2Cram.
4. Picard's validation code is too strict or unable to handle this type 
of mapping.

I'm not sure what the behavior of Bam2Cram should be in this case 
either. Right now it pretends that the reference is longer and is filled 
with Ns. But Picard apparently can't handle it. What do you think?

Vadim

**Comment by hreuver** [comment]
Hi Vadim,

The reference does exceed position 142535434 (based on the fai and the fasta). Position chr1:142535434 however is the end of the centromere so the N's seem legit. 

I don't know how Bam2Cram and Picard deal with regions such as these? Could it be that the end of the centromere is somehow misinterpreted as the end of the chromosome?

Please let me know if there is anything I can do to further clarify the situation. 

Rick

PS. We don't do the read mapping ourselves, but based on the header of the BAM files and the index file of the reference file we use, the same reference sequence was used for alligning, converting BAM to CRAM and validating the CRAM file.

**Comment by vadimzalunin** [comment]
I don't think it matters what part of reference is there as long as 
there are ACGTN characters there.
The exception claims that the reference sequence is shorter than 
142535435. Could you please extract the sequence from the fasta file and 
ensure it is longer than that? For example:
samtools faidx <the fasta file> <the sequence name> | grep -v '^>' | tr 
-d [:alpha:] | wc -c

What is this number? It should match the second column in the fai file. 
If the sequence is indeed longer than 142535435, then the bug is 
somewhere in the code loading the ref sequence and I would have to 
investigate how this is even possible.

Vadim

**Comment by hreuver** [comment]
When I run samtools faidx hg19_with_contigs.fa chr1 | grep -v '^>' | tr -d [:cntrl:] | wc -c the result is identical to the number we see in the index file (249250621).

**Comment by vadimzalunin** [comment]
please send it to vadim at ebi.ac.uk
also i'm gonna need the reference file, is it available online somewhere?

**Comment by vadimzalunin** [comment]
have you sent the file? just checking in case email got stuck in some file size filter.

**Comment by hreuver** [comment]
It has been and still is pretty busy around here, so I haven't send you the data yet. And I have some additional tests I would like to run myself. I will come back on it in the beginning of next week.
