### ISSUE TITLE
Cramtools 3.0 decoding error

### ISSUE THREAD

**Issue by jkbonfield** [enasequence/cramtools#22]
A file containing just the two reads mentioned in https://github.com/enasequence/cramtools/issues/21 caused cramtools to have a decoding failure.

Cramtools generated the CRAM (v3.0) just fine, but on decoding produces this error:

```
java -Xmx4000m -jar ~/work/cram/cramtools/cramtools-3.0.jar bam -R /nfs/srpipe_references/references/Human/1000Genomes_hs37d5/all/fasta/hs37d5.fa -I _.cram
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sf.cram.CramTools.invoke(CramTools.java:93)
        at net.sf.cram.CramTools.main(CramTools.java:123)
Caused by: java.lang.NullPointerException
        at net.sf.cram.Cram2Bam.main(Cram2Bam.java:342)
        ... 6 more
```

Edit: now stored in Gist as a binary blob:

https://gist.github.com/jkbonfield/d4e391a8a5867d74a222/raw/50ea17ca7af6cd305052ea60ad1aab94fb73233a/_.cram

Old uuencoded form:

https://gist.githubusercontent.com/jkbonfield/d4e391a8a5867d74a222/raw/d2f8a70e2d6cec0cfa69399b64db8741f11cc70a/_.cram

**Comment by vadimzalunin** [comment]
fix a63a757ab3425b2e0f6ab7f4752516b26e43a81c
