### ISSUE TITLE
CRAM with data out of bounds causes a Java stack trace.

### ISSUE THREAD

**Issue by jkbonfield** [enasequence/cramtools#24]
Given a 10 base read aligned to base 3 of a 10 base reference (so 3 to 12 inclusive), io_lib/htslib generate the CRAM file by matching the first 8 bases and then adding explicit features for the bases overhanging the end of the reference.  (Unfortunately this sort of brokenness in alignments can occur in the wild from BWA.)

Eg from cram_dump:

```Rec 3/3 at 1,7
BF = 0 => SAM 0x0 (ret 0, out_sz 1)
CF = 3 (ret 0, out_sz 1)
RL = 10 (ret 0, out_sz 1)
AP = 1 (ret 0, out_sz 1)
RG = -1 (ret 0, out_sz 1)
RN = s2 (ret 0, out_sz 2)
Detached
MF = 0 (ret 0, out_sz 1)
NS = -1 (ret 0, out_sz 1)
NP = 0 (ret 0, out_sz 1)
TS = 0 (ret 0, out_sz 1)
TL = 0 (ret 0, out_sz 1)
FN = 2 (ret 0, out_sz 1)
  0: FC = B (ret 0, out_sz 1)
  0: FP = 9+0 = 9 (ret 0, out_sz 1)
  0: BA/QS(B) = C/9 (ret 0)
  1: FC = B (ret 0, out_sz 1)
  1: FP = 1+9 = 10 (ret 0, out_sz 1)
  1: BA/QS(B) = G/9 (ret 0)
```

This is from the c1#bounds.sam file in the htslib/test directory.

On the cram file generated by htslib, Java cramtools-2.1 and 3.0 reports an error:

```
jkb@seq3a[test/_2.1] java -Xmx4000m -jar ~/work/cram/cramtools-3.0.jar bam -R ../c1.fa -I c1#bounds.sam.cram
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sf.cram.CramTools.invoke(CramTools.java:93)
        at net.sf.cram.CramTools.main(CramTools.java:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
        at net.sf.cram.build.CramNormalizer.restoreReadBases(CramNormalizer.java:278)
        at net.sf.cram.build.CramNormalizer.normalize(CramNormalizer.java:130)
        at net.sf.cram.Cram2Bam.main(Cram2Bam.java:285)
        ... 6 more
```

**Comment by vadimzalunin** [comment]
fix: 0f8317365a4dfc1155eed19c9f65827ae79acec5

**Comment by jkbonfield** [comment]
This problem still seems to exist.

```
jkb@seq3a[htslib/test] ./test_view -t c1.fa -C c1#bounds.sam > _tmp.cram
jkb@seq3a[htslib/test] /software/bin/java -Xmx4000m -jar /nfs/users/nfs_j/jkb/work/cram/cramtools/cramtools-3.0.jar bam -R c1.fa -I _tmp.cram
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sf.cram.CramTools.invoke(CramTools.java:93)
        at net.sf.cram.CramTools.main(CramTools.java:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
        at net.sf.cram.build.CramNormalizer.restoreReadBases(CramNormalizer.java:261)
        at net.sf.cram.build.CramNormalizer.normalize(CramNormalizer.java:138)
        at net.sf.cram.Cram2Bam.main(Cram2Bam.java:288)
        ... 6 more
```

**Comment by vadimzalunin** [comment]
hopefully this time: 484289546d04b27599d6fa71e865fbcd8371eb5a

**Comment by jkbonfield** [comment]
Still failing, although maybe now it's the error reported elsewhere with "shoulder" of 10 as this is a very short reference.  I noticed that the line number is different to the original bug report.

**Comment by vadimzalunin** [comment]
weird, works for me. Any way, made another fix, please see if it works for you:
e62646cda957dcabbb845b348434c6cda7157ee6

**Comment by sfchen** [comment]
Having same issue, v2.1 

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.sf.cram.CramTools.invoke(CramTools.java:93)
	at net.sf.cram.CramTools.main(CramTools.java:123)
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 133
	at net.sf.samtools.CRAMFileReader.getFileHeader(CRAMFileReader.java:139)
	at net.sf.samtools.SAMFileReader.getFileHeader(SAMFileReader.java:389)
	at net.sf.cram.DownloadReferences.main(DownloadReferences.java:75)
	... 6 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 133
	at net.sf.cram.structure.Block.<init>(Block.java:50)
	at net.sf.cram.build.CramIO.readSAMFileHeader(CramIO.java:496)
	at net.sf.cram.build.CramIO.readCramHeader(CramIO.java:314)
	at net.sf.samtools.CRAMFileReader.readHeader(CRAMFileReader.java:84)
	at net.sf.samtools.CRAMFileReader.getFileHeader(CRAMFileReader.java:137)
	... 8 more

**Comment by fleharty** [comment]
I also have this issue, but in 3.0
09:52:37:gsa2:scripts 1017 $ java -jar cramtools-3.0/cramtools-3.0.jar cram -I NA128781mb.bam -O NA128781mb.cram -R /seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.sf.cram.CramTools.invoke(CramTools.java:91)
	at net.sf.cram.CramTools.main(CramTools.java:121)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/CountingOutputStream
	at htsjdk.samtools.cram.build.CramIO.writeContainerForSamFileHeader(CramIO.java:247)
	at htsjdk.samtools.cram.build.CramIO.writeCramHeader(CramIO.java:161)
	at net.sf.cram.Bam2Cram.main(Bam2Cram.java:405)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.CountingOutputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 9 more

**Comment by zyxue** [comment]
If I only have java7, which version of cramtools should I use, please?
