### ISSUE TITLE
Regression: some v2.1 files cannot be decoded by 3.0

### ISSUE THREAD

**Issue by jkbonfield** [enasequence/cramtools#33]
ce#5b.sam.cram and xx#unsorted.sam.cram produced by htslib test_view with file format version 2.1 cannot be decoded by cramtools-3.0.jar.  The cramtools-2.1.jar can decode these.

This is probably the most important problem to fix with 3.0 as most of the other bugs I've reported have now either been fixed or affected 2.1 too (so it's not a regression, just a corner case never covered).

The stack traces are similar:

ce#5b.sam.cram
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sf.cram.CramTools.invoke(CramTools.java:93)
        at net.sf.cram.CramTools.main(CramTools.java:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at net.sf.cram.build.CramNormalizer.restoreReadBases(CramNormalizer.java:255)
        at net.sf.cram.build.CramNormalizer.normalize(CramNormalizer.java:133)
        at net.sf.cram.Cram2Bam.main(Cram2Bam.java:287)
        ... 6 more

xx#unsorted.sam.cram
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sf.cram.CramTools.invoke(CramTools.java:93)
        at net.sf.cram.CramTools.main(CramTools.java:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at net.sf.cram.build.CramNormalizer.restoreReadBases(CramNormalizer.java:240)
        at net.sf.cram.build.CramNormalizer.normalize(CramNormalizer.java:133)
        at net.sf.cram.Cram2Bam.main(Cram2Bam.java:287)
        ... 6 more

I'll email you the two files and their references.

**Comment by vadimzalunin** [comment]
fix: eb6667d15e644de7d49ceb6077ea60bc2f4cb6fd
