### ISSUE TITLE
NPE in Cram2Bam for refid -2

### ISSUE THREAD

**Issue by vadimzalunin** [enasequence/cramtools#38]
Caused by: java.lang.IllegalArgumentException: Reference index -2 not found in sequence dictionary.
        at net.sf.samtools.SAMRecord.setReferenceIndex(SAMRecord.java:367)
        at net.sf.cram.Cram2Bam.main(Cram2Bam.java:317)
        ... 6 more
Caused by: java.lang.NullPointerException
        at net.sf.samtools.SAMRecord.setReferenceIndex(SAMRecord.java:365)

Looks like slices with ref id -2 are not handled correctly: Cram2Bam tries to set refid in SAMRecord but it is not a valid refid.

**Comment by vadimzalunin** [comment]
not reproducible in cramtools3
