### ISSUE TITLE
3.0 noclassdef errors

### ISSUE THREAD

**Issue by lonestar21** [enasequence/cramtools#42]
Hi. 
I tried cramtools for the first time this morning.  Running 3.0 I go the following error:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.sf.cram.CramTools.invoke(CramTools.java:91)
	at net.sf.cram.CramTools.main(CramTools.java:121)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/CountingOutputStream
	at htsjdk.samtools.cram.build.CramIO.writeContainerForSamFileHeader(CramIO.java:247)
	at htsjdk.samtools.cram.build.CramIO.writeCramHeader(CramIO.java:161)
	at net.sf.cram.Bam2Cram.main(Bam2Cram.java:405)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.CountingOutputStream
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 9 more

Command:
java -jar  cramtools-3.0.jar cram -I A52294.sorted.bam -Q -O A52294.sorted.bam.cram -n -R /genome/GRCh37-lite.fa -l INFO

Using 2.1 I've been able to cram a bam without error

**Comment by vadimzalunin** [comment]
Is this the latest version? I just checked and the class is in the jar file. 
> java -jar cramtools-3.0.jar
Version 3.0-b38

**Comment by lonestar21** [comment]
Hi Vadim,

I think I downloaded the release version from github which is

"Version 3.0-b30"

thanks,
Richard

**Comment by vadimzalunin** [comment]
@lonestar21 
please try the latest jar

**Comment by lonestar21** [comment]
Thanks Vadim,
That works.

**Comment by vadimzalunin** [comment]
@MazdaX 
Could you please explain why you need that specific build? Chances are it has never even been published. Maybe there is another way to solve your problem?

**Comment by MazdaX** [comment]
@vadimzalunin 
As you mentioned in the reply to noclass def error in this thread I assumed that is the solution to deal with this output error:
 
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.sf.cram.CramTools.invoke(CramTools.java:91)
        at net.sf.cram.CramTools.main(CramTools.java:121)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/CountingOutputStream
        at htsjdk.samtools.cram.build.CramIO.writeContainerForSamFileHeader(CramIO.java:247)
        at htsjdk.samtools.cram.build.CramIO.writeCramHeader(CramIO.java:161)
        at net.sf.cram.Bam2Cram.main(Bam2Cram.java:405)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.CountingOutputStream
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

I'm just trying to convert BAM to CRAM using a ref fasta on a Java 8 JDK on SGE grid cluster machine. 
Is there any other version of converting BAM to CRAM?

**Comment by vadimzalunin** [comment]
@MazdaX 
I just tried the latest jar b202, seems to work fine: 
https://github.com/enasequence/cramtools/blob/master/cramtools-3.0.jar?raw=true
