### ISSUE TITLE
Unindexed FASTA might lead to NPE

### ISSUE THREAD

**Issue by superbobry** [enasequence/cramtools#45]
Using a FASTA file without index causes NPE in `Bam2Cram`, because all of the options in `ReferenceSource#getReferenceBases` fail:

```java
ref = referenceSource.getReferenceBases(samSequenceRecord, true);  // null.
log.debug(String.format("Creating tracks for reference: name=%s, length=%d.\n",
        samSequenceRecord.getSequenceName(), ref.length));  // NPE!
```

Validated for both the `v3.0` release and the `master` version

**Comment by iromeo** [comment]
Same issue, fails with NPE
```
 java -jar ./tools/cramtools-3.0.jar cram --input-bam-file ./BSSeq_HF33_GSM1973810_hg38.bam --reference-fasta-file ./indexes/hg38.fa --output-cram-file ./BSSeq_HF33_GSM1973810_hg38.cram
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at net.sf.cram.CramTools.invoke(CramTools.java:91)
        at net.sf.cram.CramTools.main(CramTools.java:121)
Caused by: java.lang.NullPointerException
        at net.sf.cram.Bam2Cram.main(Bam2Cram.java:372)
        ... 6 more
```
