### ISSUE TITLE
Index piped cram file

### ISSUE THREAD

**Issue by GWarsow** [enasequence/cramtools#51]
According to the help for the indexing option of cramtools, I a allowed to create a crai for streamed data:

```
Version 3.0-b12

Usage: <main class> [options]
  Options:    --bam-style-index  Choose between BAM index (bai) and CRAM index (crai).  (default: false)
    --help, -h         Print help and exit. (default: false)
    --input-file, -I   Path to a BAM or CRAM file to be indexed. Omit if standard input (pipe).
    -l, --log-level    Change log level: DEBUG, INFO, WARNING, ERROR. (default: ERROR)
```

However, if I leave the -I parameter away, I get either the help screen or when I call it with log-level debug (-l DEBUG), I will get a NullPointerException for the FileInputStream:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at net.sf.cram.CramTools.invoke(CramTools.java:93)
   at net.sf.cram.CramTools.main(CramTools.java:123)
Caused by: java.lang.NullPointerException
   at java.io.FileInputStream.<init>(FileInputStream.java:130)
   at net.sf.samtools.CRAMFileReader.isCRAMFile(CRAMFileReader.java:331)
   at net.sf.cram.index.CramIndexer.main(CramIndexer.java:78)
   ... 6 more
```

Am I missing something or is the option to create a crai for a streamed cram file just a copy and paste error from e.g. cramtools bam/cram (conversion parts of cramtools)?

**Comment by vadimzalunin** [comment]
Sorry, the description is misleading! The code to support standard input has been removed in favor of htsjdk indexing mechanism which relies on files. 
It should be straightforward to revive this feature if there is enough interest. Could you please describe how it may be useful?

**Comment by GWarsow** [comment]
Thanks for the fast reply! I would like to integrate cram file generation into our pipelines. It is intended to align read data from fastq files with bwa-mem and pipe the resulting bam file to several consumption tasks, e.g. QC, and in the end pipe the bam file stream into cramtools cram in order convert the (coordinate-sorted) bam stream to `cramttols cram` to get a cram file (on hard disk) and cram stream (via tee)) while simultaneously, as the cram file is being built, the cram stream is consumed by `cram idex` in oder to build the crai (to file on hard disk).

**Comment by GWarsow** [comment]
Hi Vadim, when do you think could it be possible to have a cramtools release that is able to index piped cram files?

**Comment by vadimzalunin** [comment]
@GWarsow please try the latest version. You will need to rebuild the jar file though. On a side note, the options of the index command changed slightly.

**Comment by GWarsow** [comment]
@vadimzalunin Hi Vadim, it seems to work fine. Thank you very much!
