### ISSUE TITLE
BAM to CRAM conversion: Error:New position is beyond the reference: 1

### ISSUE THREAD

**Issue by antozito** [enasequence/cramtools#52]
Hi all, 

I am trying to convert a BAM to CRAM and CRAMtools produces the following error:
$: java -jar cramtools-1.0-b357/cramtools-1.0.jar cram --input-bam-file  input.bam --referencefasta-file   GCA_000001405.15_GRCh38_genomic.fa --output-cram-file output.cram

Exception in thread "main" java.lang.RuntimeException: New position is beyond the reference: 1

Any help?
many thanks in advance
anto

**Comment by vadimzalunin** [comment]
Hello, 
It looks like you are using a very old version of cramtools. Please try this one: 
https://github.com/enasequence/cramtools/blob/master/cramtools-3.0.jar

**Comment by antozito** [comment]
Hi @vadimzalunin 
 
Once obtained the cram, can you suggest me some efficient way to compress it achieving a good memory saving? It seems to be quite hard to do that

Best regards
anto

**Comment by antozito** [comment]
Hi @vadimzalunin 
when trying to converting the bam to bam, I get the follwing errors:

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at net.sf.cram.CramTools.invoke(CramTools.java:91)
	at net.sf.cram.CramTools.main(CramTools.java:121)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/CountingOutputStream
	at htsjdk.samtools.cram.build.CramIO.writeContainerForSamFileHeader(CramIO.java:247)
	at htsjdk.samtools.cram.build.CramIO.writeCramHeader(CramIO.java:161)
	at net.sf.cram.Bam2Cram.main(Bam2Cram.java:405)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.CountingOutputStream
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 9 more

What error is due to ?
thanks for the support
Best
anto
