### ISSUE TITLE
Count records in *.cram fails with FileNotFoundException

### ISSUE THREAD

**Issue by iromeo** [enasequence/cramtools#53]
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: http://www.ebi.ac.uk/ena/cram/md5/2648ae1bacce4ec4b6cf337dcae37816

```
java -jar cramtools-3.0.jar bam -I ./GSM1973810.cram -c
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at net.sf.cram.CramTools.invoke(CramTools.java:91)
        at net.sf.cram.CramTools.main(CramTools.java:121)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: http://www.ebi.ac.uk/ena/cram/md5/2648ae1bacce4ec4b6cf337dcae37816
        at net.sf.cram.ref.ReferenceSource.findBases(ReferenceSource.java:184)
        at net.sf.cram.ref.ReferenceSource.getReferenceBases(ReferenceSource.java:128)
        at net.sf.cram.FixBAMFileHeader.fixSequence(FixBAMFileHeader.java:55)
        at net.sf.cram.FixBAMFileHeader.fixSequences(FixBAMFileHeader.java:48)
        at net.sf.cram.Cram2Bam.main(Cram2Bam.java:120)
        ... 6 more
Caused by: java.io.FileNotFoundException: http://www.ebi.ac.uk/ena/cram/md5/2648ae1bacce4ec4b6cf337dcae37816
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1834)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
        at java.net.URL.openStream(URL.java:1038)
        at net.sf.cram.ref.ReferenceSource.loadFromPath(ReferenceSource.java:250)
        at net.sf.cram.ref.ReferenceSource.findBasesByMD5(ReferenceSource.java:287)
        at net.sf.cram.ref.ReferenceSource.findBases(ReferenceSource.java:180)
        ... 10 more
```
P.S.: Works ok, if reference (hg38) is specified.

**Comment by vadimzalunin** [comment]
version?

**Comment by vadimzalunin** [comment]
ah, yes, found it! Try --skip-md5-check. 

I'm going to issue a patch, just a sec...

**Comment by iromeo** [comment]
> Try --skip-md5-check.
Thx, this helps

**Comment by vadimzalunin** [comment]
On a second thought, not going to change the code right now because of multiref containers. In theory counting reads and bases should not require reference sequence, but in practice it is all entangled.

**Comment by jkbonfield** [comment]
On Mon, Mar 14, 2016 at 04:50:38AM -0700, Vadim Zalunin wrote:
> On a second thought, not going to change the code right now because of multiref containers. In theory counting reads and bases should not require reference sequence, but in practice it is all entangled. 

I think this is perhaps an omission from the index.  It's not
technically needed for indexing, but it is a useful field to have (eg
see "samtools idxstats" on .BAI which can do this) and consulting the
index for a rapid identification of coverage or counts is worthwhile.

Maybe we can add it to a wishlist for the index file format to review
whenever we make a new CRAM spec release.

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by vadimzalunin** [comment]
@jkbonfield I totally agree, index should have counts. 
I meant to say that counting with flag filters should not require references but this is not possible at the moment with cramtools.

**Comment by levipierce** [comment]
I also got this problem.

**Comment by EmilyHMWong** [comment]
I got the same problem even I used --skip-md5-check.
cramtools version 3.0

java -jar /root/cram/cramtools/cramtools-3.0.jar bam \
    -I /root/cram/test.cram \
    --reference-fasta-file /root/cram/genome.fa \
    --skip-md5-check \
    -O /root/cram/test.cram.bam

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.sf.cram.CramTools.invoke(CramTools.java:91)
        at net.sf.cram.CramTools.main(CramTools.java:121)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: http://www.ebi.ac.uk/ena/cram/md5/bd85195c4feed92050f02aabe5664435
        at net.sf.cram.ref.ReferenceSource.getRegion(ReferenceSource.java:201)
        at net.sf.cram.Cram2Bam.main(Cram2Bam.java:218)
        ... 6 more
Caused by: java.io.FileNotFoundException: http://www.ebi.ac.uk/ena/cram/md5/bd85195c4feed92050f02aabe5664435
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.URL.openStream(URL.java:1045)
        at net.sf.cram.ref.ReferenceSource.loadFromPath(ReferenceSource.java:320)
        at net.sf.cram.ref.ReferenceSource.findBasesByMD5(ReferenceSource.java:366)
        at net.sf.cram.ref.ReferenceSource.getRegion(ReferenceSource.java:197)
        ... 7 more

**Comment by levipierce** [comment]
Is there any fix for this the option --skip-md5-check does not seem to work...

**Comment by levipierce** [comment]
Emily and I were able to run this successfully with version 2.1 of cramtools.  I don't see any tests in the git repo?  I would be happy to start to add some in for integration test purposes...

Cheers,
~LP
