### ISSUE TITLE
CRAM to BAM fail on large file

### ISSUE THREAD

**Issue by Arkarachai** [enasequence/cramtools#60]
Hi,
I have CRAM file of about 35G and I tried to convert it back to BAM. I used 32 cores machine, but it seems that only 1 core is doing a job. After ~20-30 mins there is no CPU activity and it was like that for a day, so I decided to terminate the analysis.

Is there a limited file size of CRAM that I can convert back to BAM? Also, is there a way to utilize more core?

Thanks,
Chai

**Comment by vadimzalunin** [comment]
Please make sure there is enough memory, I'd recommend at least 4gb. 
The new version has a new converter: 
java -cp cramtools-3.0.jar htsjdk.samtools.cram.paralell.CramToBam

this allows to utilize multiple cores but in practice ~16 cores is enough due to performance saturation.

**Comment by Arkarachai** [comment]
Thanks, Vadim. Is there a manual for your tool? I only found short description in github.

**Comment by vadimzalunin** [comment]
At the moment only command line help I'm afraid. Let me know if you have questions about usage.

**Comment by Arkarachai** [comment]
Hi Vadim,
Where could I find the htsjdk.samtools.cram.paralell.CramToBam? It seems that it's not included in your github.

**Comment by vadimzalunin** [comment]
please try running it like this: 
java -cp cramtools-3.0.jar htsjdk.samtools.cram.paralell.CramToBam

**Comment by Arkarachai** [comment]
Thanks Vamin. The speed for parallel version is quite impressive. Do you have the command for BAM to CRAM in parallel running as well?

**Comment by vadimzalunin** [comment]
please try:
java -cp cramtools-3.0.jar htsjdk.samtools.cram.paralell.BamToCram

**Comment by Arkarachai** [comment]
Hi Vamin,
I got the following error once I run it.

> java -cp cramtools/cramtools-3.0.jar htsjdk.samtools.cram.paralell.BamToCram --input-bam-file infile.bam --reference-fasta-file genome.fa --output-cram-file out.cram --capture-tags
> Failed to parse parameteres, detailed message below: 
> 7
> 

It seems that -Q and -n are not supported here as well. Is it possible to do lossless compression using htsjdk.samtools.cram.paralell.BamToCram? Also, I wonder if htsjdk.samtools.cram.paralell.BamToCram is part of cramtools or samtools?

Thanks,
Chai

**Comment by vadimzalunin** [comment]
Yes, in this version lossy tags only, quality scores and read names are lossless. 

This is part of cramtools for now.

**Comment by Arkarachai** [comment]
Thanks Vamin. When I used this following command, the process is pausing.  (note that `nproc` here is 8. I use 8 core machine).

time java -cp cramtools/cramtools-3.0.jar htsjdk.samtools.cram.paralell.BamToCram --threads `nproc` --input-bam-file infile.bam --reference-fasta-file genome.fa --output-cram-file out2.cram --capture-all-tags

Below here is the screen that I see. These are generated instantly. No progress after that.

INFO    2016-07-27 20:33:01     BamToCram       thread pool size=7, converion threads=4, queues capacity=8
INFO    2016-07-27 20:33:01     BamToCram       Creating thread pool with size 7
INFO    2016-07-27 20:33:01     Job     Starting job: htsjdk.samtools.cram.paralell.StreamPump, name: BGZF_UNC_PUMP
INFO    2016-07-27 20:33:01     BamToCram_OBA_Function  converter created
INFO    2016-07-27 20:33:01     BamToCram_OBA_Function  converter created
INFO    2016-07-27 20:33:01     BamToCram_OBA_Function  converter created
INFO    2016-07-27 20:33:01     BamToCram_OBA_Function  converter created
INFO    2016-07-27 20:33:01     Job     Starting job: htsjdk.samtools.cram.paralell.SupplierJob, name: BAM_SLICER_SUPPLIER
INFO    2016-07-27 20:33:01     Job     Starting job: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_0
INFO    2016-07-27 20:33:01     Job     Starting job: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_1
INFO    2016-07-27 20:33:01     Job     Starting job: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_2
INFO    2016-07-27 20:33:01     Job     Starting job: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_3
INFO    2016-07-27 20:33:01     Job     Starting job: htsjdk.samtools.cram.paralell.ConsumerJob, name: CRAM_BYTE_WRITE_JOB
java.lang.NullPointerException
        at htsjdk.samtools.cram.CramContext.<init>(CramContext.java:38)
        at htsjdk.samtools.cram.CramSerilization.convert(CramSerilization.java:44)
        at htsjdk.samtools.cram.paralell.BamToCram_OBA_Function.apply(BamToCram_OBA_Function.java:67)
        at htsjdk.samtools.cram.paralell.BamToCram_OBA_Function.apply(BamToCram_OBA_Function.java:24)
        at htsjdk.samtools.cram.paralell.TransformerJob.doRun(TransformerJob.java:28)
        at htsjdk.samtools.cram.paralell.Job.run(Job.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
        at htsjdk.samtools.cram.CramContext.<init>(CramContext.java:38)
        at htsjdk.samtools.cram.CramSerilization.convert(CramSerilization.java:44)
        at htsjdk.samtools.cram.paralell.BamToCram_OBA_Function.apply(BamToCram_OBA_Function.java:67)
        at htsjdk.samtools.cram.paralell.BamToCram_OBA_Function.apply(BamToCram_OBA_Function.java:24)
        at htsjdk.samtools.cram.paralell.TransformerJob.doRun(TransformerJob.java:28)
        at htsjdk.samtools.cram.paralell.Job.run(Job.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
INFO    2016-07-27 20:33:01     Job     Job done: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_2
java.lang.NullPointerException
        at htsjdk.samtools.cram.CramContext.<init>(CramContext.java:38)
        at htsjdk.samtools.cram.CramSerilization.convert(CramSerilization.java:44)
        at htsjdk.samtools.cram.paralell.BamToCram_OBA_Function.apply(BamToCram_OBA_Function.java:67)
        at htsjdk.samtools.cram.paralell.BamToCram_OBA_Function.apply(BamToCram_OBA_Function.java:24)
        at htsjdk.samtools.cram.paralell.TransformerJob.doRun(TransformerJob.java:28)
        at htsjdk.samtools.cram.paralell.Job.run(Job.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
        at htsjdk.samtools.cram.CramContext.<init>(CramContext.java:38)
        at htsjdk.samtools.cram.CramSerilization.convert(CramSerilization.java:44)
        at htsjdk.samtools.cram.paralell.BamToCram_OBA_Function.apply(BamToCram_OBA_Function.java:67)
        at htsjdk.samtools.cram.paralell.BamToCram_OBA_Function.apply(BamToCram_OBA_Function.java:24)
        at htsjdk.samtools.cram.paralell.TransformerJob.doRun(TransformerJob.java:28)
        at htsjdk.samtools.cram.paralell.Job.run(Job.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
INFO    2016-07-27 20:33:01     Job     Job done: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_3
INFO    2016-07-27 20:33:01     Job     Job done: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_1
INFO    2016-07-27 20:33:01     Job     Finished job: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_3
INFO    2016-07-27 20:33:01     Job     Finished job: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_1
INFO    2016-07-27 20:33:01     Conveyer        close: 3
INFO    2016-07-27 20:33:01     Conveyer        close: 2
INFO    2016-07-27 20:33:01     Job     Finished job: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_2
INFO    2016-07-27 20:33:01     Job     Job done: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_0
INFO    2016-07-27 20:33:01     Conveyer        close: 1
INFO    2016-07-27 20:33:01     Job     Finished job: htsjdk.samtools.cram.paralell.TransformerJob, name: BC_CONVERTER_0
INFO    2016-07-27 20:33:01     Conveyer        close: 0
INFO    2016-07-27 20:33:01     Job     Job done: htsjdk.samtools.cram.paralell.ConsumerJob, name: CRAM_BYTE_WRITE_JOB
INFO    2016-07-27 20:33:01     Job     Finished job: htsjdk.samtools.cram.paralell.ConsumerJob, name: CRAM_BYTE_WRITE_JOB

**Comment by vadimzalunin** [comment]
I have pushed a fix, please try again with a fresh jar.
