### ISSUE TITLE
cram to bam conversion error

### ISSUE THREAD

**Issue by blueagave** [enasequence/cramtools#70]
I have a user who is attempting to convert a cram file into a bam file, but getting the error below.  Do you have any suggestions?

Environment:

RHEL 7.1
openjdk 1.8.0_101
cramtools-3.0

Command and resulting error:

$ java -jar /usr/local/packages/cramtools/cramtools-3.0.jar bam -I 21136_1#1.cram -R /local/projects-t3/SerreDLab-3/kima7/genomes/p_vivax_P01/PlasmoDB-29_PvivaxP01_Genome.fasta -O test.bam
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sf.cram.CramTools.invoke(CramTools.java:91)
	at net.sf.cram.CramTools.main(CramTools.java:121)
Caused by: java.lang.NullPointerException
	at htsjdk.samtools.cram.build.CramIO.readFormatDefinition(CramIO.java:168)
	at htsjdk.samtools.cram.build.CramIO.readCramHeader(CramIO.java:189)
	at net.sf.cram.Cram2Bam.main(Cram2Bam.java:113)
	... 6 more

Thanks
Tom

**Comment by jkbonfield** [comment]
This is one of our (Sanger's) CRAM files, produced by Scramble.  So I thought I'd double check it just incase.

I can decode our local copy just fine with both Scramble and Cramtools (Version 3.0-b208).  The local copy of this cram file has this md5sum:

```
36c622c3f0b65e684c35efdaa808c851  21136_1#1.cram
```

I'm not sure b208 is the latest cramtools, but it's what I had checked out.  It'd help Vadim perhaps if you quoted the exact version of yours (it's at the top of the usage help).
