### ISSUE TITLE
Cramtools merge error

### ISSUE THREAD

**Issue by HovhannesSahakyan** [enasequence/cramtools#75]
**Hi everybody,**

**I try to merge .cram files downloaded from EGA. It is impossible to run cramtools-3.**

/storage/software/jdk-1.8.0-25/bin/java -jar /folder/cramtools-3/cramtools/cramtools-3.0.jar merge _EGAR00001165141_11009_5#9.cram _EGAR00001166863_11083_2#9.cram _EGAR00001166869_11083_4#9.cram _EGAR00001166875_11083_6#9.cram _EGAR00001166881_11083_8#9.cram _EGAR00001166860_11083_1#9.cram _EGAR00001166866_11083_3#9.cram _EGAR00001166872_11083_5#9.cram _EGAR00001166878_11083_7#9.cram --output-file /folder/Egyptian_09.cram --reference-fasta-file /folder/ref37/hs37d5.fa

**It gives the following error.**

Adding ref pattern: http://www.ebi.ac.uk/ena/cram/md5/%s
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.sf.cram.CramTools.invoke(CramTools.java:91)
	at net.sf.cram.CramTools.main(CramTools.java:121)
Caused by: java.lang.IllegalStateException: A valid CRAM reference was not supplied and one cannot be acquired via the property settings reference_fasta or use_cram_ref_download
	at htsjdk.samtools.cram.ref.ReferenceSource.getDefaultCRAMReferenceSource(ReferenceSource.java:107)
	at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:73)
	at htsjdk.samtools.SAMFileReader.init(SAMFileReader.java:674)
	at htsjdk.samtools.SAMFileReader.<init>(SAMFileReader.java:161)
	at htsjdk.samtools.SAMFileReader.<init>(SAMFileReader.java:116)
	at net.sf.cram.Merge.readFiles(Merge.java:214)
	at net.sf.cram.Merge.main(Merge.java:106)
	... 6 more

**Cramtools-2.1 works but until some point and gives error as well.

Please help me to solve the problem.**

Best wishes,
Hovhannes

**Comment by vadimzalunin** [comment]
It's a known issue due to ENA reference service switching to HTTPS. Should
be fixed in the next release.

Vadim

**Comment by HovhannesSahakyan** [comment]
Thank you for quick response. 

Is there some approximate date when the next release will come out?

And it would be nice to write somewhere, maybe in the README file or in the github page of the program, about this issue.

Best,
Hovhannes

**Comment by vadimzalunin** [comment]
I'll push for this or early next week.

**Comment by HovhannesSahakyan** [comment]
Hi Vadim,

Any news about the next release?

Best,
Hovhannes

**Comment by HovhannesSahakyan** [comment]
Please let me know the approximate date of the next release.
